# Generated by Django 2.1.4 on 2019-01-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('label', models.CharField(max_length=100)),
                ('milestone', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='issuses',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_api.Repos'),
        ),
        migrations.AddField(
            model_name='branches',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_api.Repos'),
        ),
    ]
