# Generated by Django 2.1.4 on 2018-12-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=32)),
                ('github_name', models.CharField(max_length=100)),
                ('github_password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('label', models.CharField(max_length=100)),
                ('milestone', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='issuses',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_api.Repos'),
        ),
        migrations.AddField(
            model_name='branches',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_api.Repos'),
        ),
    ]
