# Generated by Django 2.1.4 on 2019-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitauthentication',
            name='access_token',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
