# Generated by Django 2.1.4 on 2019-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_api', '0002_auto_20190201_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
