# Generated by Django 2.1.4 on 2019-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_api', '0003_auto_20190202_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
